/* Generated By:JavaCC: Do not edit this line. LexicalAnalysisConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicalAnalysisConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int IS = 12;
  /** RegularExpression Id. */
  int AS = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int ALL = 15;
  /** RegularExpression Id. */
  int THIS = 16;
  /** RegularExpression Id. */
  int BODY = 17;
  /** RegularExpression Id. */
  int TYPE = 18;
  /** RegularExpression Id. */
  int REAL = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int LOGIC = 21;
  /** RegularExpression Id. */
  int ENUM = 22;
  /** RegularExpression Id. */
  int READ = 23;
  /** RegularExpression Id. */
  int WRITE = 24;
  /** RegularExpression Id. */
  int REPEAT = 25;
  /** RegularExpression Id. */
  int VARIABLE = 26;
  /** RegularExpression Id. */
  int CONSTANT = 27;
  /** RegularExpression Id. */
  int RESULT = 28;
  /** RegularExpression Id. */
  int INTEGER = 29;
  /** RegularExpression Id. */
  int AVALIATE = 30;
  /** RegularExpression Id. */
  int DESCRIPTION = 31;
  /** RegularExpression Id. */
  int DECLARATION = 32;
  /** RegularExpression Id. */
  int DESIGNATE = 33;
  /** RegularExpression Id. */
  int TRUE = 34;
  /** RegularExpression Id. */
  int UNTRUE = 35;
  /** RegularExpression Id. */
  int NOT_EQUAL = 36;
  /** RegularExpression Id. */
  int ATTRIBUTION = 37;
  /** RegularExpression Id. */
  int EQUAL = 38;
  /** RegularExpression Id. */
  int GREATERTHEN = 39;
  /** RegularExpression Id. */
  int LESSTHEN = 40;
  /** RegularExpression Id. */
  int LESS_EQUALS = 41;
  /** RegularExpression Id. */
  int GREATER_EQUALS = 42;
  /** RegularExpression Id. */
  int OR_LOGIC = 43;
  /** RegularExpression Id. */
  int AND_LOGIC = 44;
  /** RegularExpression Id. */
  int NEGATE_LOGIC = 45;
  /** RegularExpression Id. */
  int PLUS = 46;
  /** RegularExpression Id. */
  int SUBTRACTION = 47;
  /** RegularExpression Id. */
  int MULTIPLY = 48;
  /** RegularExpression Id. */
  int DIVISION = 49;
  /** RegularExpression Id. */
  int INTEGER_DIVISION = 50;
  /** RegularExpression Id. */
  int DIVISION_REMAINDER = 51;
  /** RegularExpression Id. */
  int POTENCE = 52;
  /** RegularExpression Id. */
  int SEMI_COLUMN = 53;
  /** RegularExpression Id. */
  int DOT = 54;
  /** RegularExpression Id. */
  int OPEN_KEYS = 55;
  /** RegularExpression Id. */
  int CLOSE_KEYS = 56;
  /** RegularExpression Id. */
  int OPEN_BOX = 57;
  /** RegularExpression Id. */
  int CLOSE_BOX = 58;
  /** RegularExpression Id. */
  int OPEN_BRACKETS = 59;
  /** RegularExpression Id. */
  int CLOSE_BRACKETS = 60;
  /** RegularExpression Id. */
  int IDENTIFIER = 61;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 62;
  /** RegularExpression Id. */
  int INTEGER_NUMERICAL_CONSTANT = 63;
  /** RegularExpression Id. */
  int REAL_NUMERICAL_CONSTANT = 64;
  /** RegularExpression Id. */
  int DIGIT = 65;
  /** RegularExpression Id. */
  int SYMBOL = 66;
  /** RegularExpression Id. */
  int MINUS = 67;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 68;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 69;
  /** RegularExpression Id. */
  int LETTER = 70;
  /** RegularExpression Id. */
  int SMALL_LETTER = 71;
  /** RegularExpression Id. */
  int CAPITAL_LETTER = 72;
  /** RegularExpression Id. */
  int ASCII = 73;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"do\"",
    "\"is\"",
    "\"as\"",
    "\"and\"",
    "\"all\"",
    "\"this\"",
    "\"body\"",
    "\"type\"",
    "\"real\"",
    "\"string\"",
    "\"logic\"",
    "\"enum\"",
    "\"read\"",
    "\"write\"",
    "\"repeat\"",
    "\"variable\"",
    "\"constant\"",
    "\"result\"",
    "\"integer\"",
    "\"avaliate\"",
    "\"description\"",
    "\"declaration\"",
    "\"designate\"",
    "\"true\"",
    "\"untrue\"",
    "\"!=\"",
    "\"=\"",
    "\"==\"",
    "\">>\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>=\"",
    "\"|\"",
    "\"&\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"%%\"",
    "\"**\"",
    "\",\"",
    "\".\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "<LITERAL_CONSTANT>",
    "<INTEGER_NUMERICAL_CONSTANT>",
    "<REAL_NUMERICAL_CONSTANT>",
    "<DIGIT>",
    "<SYMBOL>",
    "<MINUS>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<LETTER>",
    "<SMALL_LETTER>",
    "<CAPITAL_LETTER>",
    "<ASCII>",
  };

}
