package LexicalAnalysis;/* Generated By:JavaCC: Do not edit this line. LexicalAnalysisConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicalAnalysisConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOLS = 11;
  /** RegularExpression Id. */
  int RESERVED_WORD = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 14;
  /** RegularExpression Id. */
  int INTEGER_NUMERICAL_CONSTANT = 15;
  /** RegularExpression Id. */
  int REAL_NUMERICAL_CONSTANT = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int SYMBOL = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 20;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int SMALL_LETTER = 23;
  /** RegularExpression Id. */
  int CAPITAL_LETTER = 24;
  /** RegularExpression Id. */
  int ASCII = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "<SPECIAL_SYMBOLS>",
    "<RESERVED_WORD>",
    "<IDENTIFIER>",
    "<LITERAL_CONSTANT>",
    "<INTEGER_NUMERICAL_CONSTANT>",
    "<REAL_NUMERICAL_CONSTANT>",
    "<DIGIT>",
    "<SYMBOL>",
    "<MINUS>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<LETTER>",
    "<SMALL_LETTER>",
    "<CAPITAL_LETTER>",
    "<ASCII>",
  };

}
