package parser;/* Generated By:JavaCC: Do not edit this line. LangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int IS = 13;
  /** RegularExpression Id. */
  int AS = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int ALL = 16;
  /** RegularExpression Id. */
  int THIS = 17;
  /** RegularExpression Id. */
  int BODY = 18;
  /** RegularExpression Id. */
  int TYPE = 19;
  /** RegularExpression Id. */
  int REAL = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int LOGIC = 22;
  /** RegularExpression Id. */
  int ENUM = 23;
  /** RegularExpression Id. */
  int READ = 24;
  /** RegularExpression Id. */
  int WRITE = 25;
  /** RegularExpression Id. */
  int REPEAT = 26;
  /** RegularExpression Id. */
  int VARIABLE = 27;
  /** RegularExpression Id. */
  int CONSTANT = 28;
  /** RegularExpression Id. */
  int RESULT = 29;
  /** RegularExpression Id. */
  int INTEGER = 30;
  /** RegularExpression Id. */
  int AVALIATE = 31;
  /** RegularExpression Id. */
  int DESCRIPTION = 32;
  /** RegularExpression Id. */
  int DECLARATION = 33;
  /** RegularExpression Id. */
  int DESIGNATE = 34;
  /** RegularExpression Id. */
  int TRUE = 35;
  /** RegularExpression Id. */
  int UNTRUE = 36;
  /** RegularExpression Id. */
  int OR_LOGIC = 37;
  /** RegularExpression Id. */
  int AND_LOGIC = 38;
  /** RegularExpression Id. */
  int NEGATE_LOGIC = 39;
  /** RegularExpression Id. */
  int PLUS = 40;
  /** RegularExpression Id. */
  int SUBTRACTION = 41;
  /** RegularExpression Id. */
  int MULTIPLY = 42;
  /** RegularExpression Id. */
  int DIVISION = 43;
  /** RegularExpression Id. */
  int INTEGER_DIVISION = 44;
  /** RegularExpression Id. */
  int DIVISION_REMAINDER = 45;
  /** RegularExpression Id. */
  int POTENCE = 46;
  /** RegularExpression Id. */
  int NOT_EQUAL = 47;
  /** RegularExpression Id. */
  int ATTRIBUTION = 48;
  /** RegularExpression Id. */
  int EQUAL = 49;
  /** RegularExpression Id. */
  int GREATER_THEN = 50;
  /** RegularExpression Id. */
  int LESS_THEN = 51;
  /** RegularExpression Id. */
  int LESS_EQUALS = 52;
  /** RegularExpression Id. */
  int GREATER_EQUALS = 53;
  /** RegularExpression Id. */
  int OPEN_KEYS = 54;
  /** RegularExpression Id. */
  int CLOSE_KEYS = 55;
  /** RegularExpression Id. */
  int OPEN_BOX = 56;
  /** RegularExpression Id. */
  int CLOSE_BOX = 57;
  /** RegularExpression Id. */
  int OPEN_BRACKETS = 58;
  /** RegularExpression Id. */
  int CLOSE_BRACKETS = 59;
  /** RegularExpression Id. */
  int SEMI_COLUMN = 60;
  /** RegularExpression Id. */
  int DOT = 61;
  /** RegularExpression Id. */
  int IDENTIFIER = 62;
  /** RegularExpression Id. */
  int INVALID_IDENTIFIER = 63;
  /** RegularExpression Id. */
  int LITERAL_CONSTANT = 64;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_CONST = 65;
  /** RegularExpression Id. */
  int SINGLE_QUOTE_CONST = 66;
  /** RegularExpression Id. */
  int ERROR_LITERAL_CONSTANT = 67;
  /** RegularExpression Id. */
  int INTEGER_NUMERICAL_CONSTANT = 68;
  /** RegularExpression Id. */
  int REAL_NUMERICAL_CONSTANT = 69;
  /** RegularExpression Id. */
  int INVALID_INTEGER_NUMERICAL_CONSTANT = 70;
  /** RegularExpression Id. */
  int INVALID_REAL_NUMERICAL_CONSTANT = 71;
  /** RegularExpression Id. */
  int DIGIT = 72;
  /** RegularExpression Id. */
  int SYMBOL = 73;
  /** RegularExpression Id. */
  int MINUS = 74;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 75;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 76;
  /** RegularExpression Id. */
  int ASCII = 77;
  /** RegularExpression Id. */
  int SMALL_LETTER = 78;
  /** RegularExpression Id. */
  int CAPITAL_LETTER = 79;
  /** RegularExpression Id. */
  int LETTER = 80;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"do\"",
    "\"is\"",
    "\"as\"",
    "\"and\"",
    "\"all\"",
    "\"this\"",
    "\"body\"",
    "\"type\"",
    "\"real\"",
    "\"string\"",
    "\"logic\"",
    "\"enum\"",
    "\"read\"",
    "\"write\"",
    "\"repeat\"",
    "\"variable\"",
    "\"constant\"",
    "\"result\"",
    "\"integer\"",
    "\"avaliate\"",
    "\"description\"",
    "\"declaration\"",
    "\"designate\"",
    "\"true\"",
    "\"untrue\"",
    "\"|\"",
    "\"&\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"%%\"",
    "\"**\"",
    "\"!=\"",
    "\"=\"",
    "\"==\"",
    "\">>\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>=\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<INVALID_IDENTIFIER>",
    "<LITERAL_CONSTANT>",
    "<DOUBLE_QUOTE_CONST>",
    "<SINGLE_QUOTE_CONST>",
    "<ERROR_LITERAL_CONSTANT>",
    "<INTEGER_NUMERICAL_CONSTANT>",
    "<REAL_NUMERICAL_CONSTANT>",
    "<INVALID_INTEGER_NUMERICAL_CONSTANT>",
    "<INVALID_REAL_NUMERICAL_CONSTANT>",
    "<DIGIT>",
    "<SYMBOL>",
    "<MINUS>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ASCII>",
    "<SMALL_LETTER>",
    "<CAPITAL_LETTER>",
    "<LETTER>",
  };

}
